import 'dart:convert';

import '../domain/user_entity.dart';

class UserModel extends UserEntity {
  const UserModel(
      {String? emailAddress,
      String? password,
      String? phoneNumber,
      String? fullName,
      String? device_name,
      String? device_token,
      String? device_type,
      int? id,
      String? preskriber_id,
      String? pincode,
      String? documents,
      String? created_by,
      String? updated_by,
      String? created_at,
      String? updated_at,
      int? age,
      String? gender,
      String? id_number,
      String? dob,
      String? address,
      String? is_insurance,
      String? insurance_id,
      String? hmo_id,
      String? insurance_status,
      String? latitude,
      String? otp,
      String? health_data,
      String? image,
      int? role_id,
      String? expiry_ambulance,
      int? privacy_send_request,
      String? city,
      String? state,
      String? country});

  Map<String, dynamic> toMap() {
    return {
      'emailAddress': emailAddress,
      'password': password,
      'phoneNumber': phoneNumber,
      'fullName': fullName,
      'device_name': device_name,
      'device_token': device_token,
      'device_type': device_type,
      'id': id,
      'preskriber_id': preskriber_id,
      'pincode': pincode,
      'documents': documents,
      'created_by': created_by,
      'updated_by': updated_by,
      'created_at': created_at,
      'updated_at': updated_at,
      'age': age,
      'gender': gender,
      'id_number': id_number,
      'dob': dob,
      'address': address,
      'is_insurance': is_insurance,
      'insurance_id': insurance_id,
      'hmo_id': hmo_id,
      'insurance_status': insurance_status,
      'latitude': latitude,
      'otp': otp,
      'health_data': health_data,
      'image': image,
      'role_id': role_id,
      'expiry_ambulance': expiry_ambulance,
      'privacy_send_request': privacy_send_request,
      'city': city,
      'state': state,
      'country': country,
    };
  }

  factory UserModel.fromMap(Map<String, dynamic> map) {
    return UserModel(
      emailAddress: map['emailAddress'],
      password: map['password'],
      phoneNumber: map['phoneNumber'],
      fullName: map['fullName'],
      device_name: map['device_name'],
      device_token: map['device_token'],
      device_type: map['device_type'],
      id: map['id'],
      preskriber_id: map['preskriber_id'],
      pincode: map['pincode'],
      documents: map['documents'],
      created_by: map['created_by'],
      updated_by: map['updated_by'],
      created_at: map['created_at'],
      updated_at: map['updated_at'],
      age: map['age'],
      gender: map['gender'],
      id_number: map['id_number'],
      dob: map['dob'],
      address: map['address'],
      is_insurance: map['is_insurance'],
      insurance_id: map['insurance_id'],
      hmo_id: map['hmo_id'],
      insurance_status: map['insurance_status'],
      latitude: map['latitude'],
      otp: map['otp'],
      health_data: map['health_data'],
      image: map['image'],
      role_id: map['role_id'],
      expiry_ambulance: map['expiry_ambulance'],
      privacy_send_request: map['privacy_send_request'],
      city: map['city'],
      state: map['state'],
      country: map['country'],
    );
  }
  factory UserModel.fromJson(String source) =>
      UserModel.fromMap(json.decode(source));
}
